# This is a basic workflow to help you get started with Actions

name: Publish to nuget

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - uses: actions/setup-dotnet@v1
        name: Setup dotnet
        with: 
          dotnet-version: 3.1.x
      
      - name: Install dependencies
        run: dotnet restore src/R6Tab.NET/R6Tab.NET.csproj
      
      - name: Build
        run: dotnet build src/R6Tab.NET/R6Tab.NET.csproj --configuration Release --no-restore

      - uses: brandedoutcast/publish-nuget@v2.5.5
        name: Publish NuGet
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/R6Tab.NET/R6Tab.NET.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: R6Tab.NET.Api
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org
